# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
    assignees:
      - 'octocat'
    labels:
      - 'dependencies'
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: 'npm'
    reviewers:
      - 'octocat'
      - 'christoff-linde'
      - 'SchizzY'
    open-pull-requests-limit: 5
    versioning-strategy: 'increase-if-necessary'
    groups:
      prod-deps:
        dependency-type: 'production'
      dev-deps:
        dependency-type: 'development'
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "src-tauri/" # Location of package manifests
    assignees:
      - 'octocat'
    schedule:
      interval: "daily"
    labels:
      - "cargo"
      - "dependencies"
    commit-message:
      prefix: "cargo "
      include: "scope"
    groups:
      prod-deps:
        dependency-type: 'production'
      dev-deps:
        dependency-type: 'development'
